# Generated by Django 3.1.1 on 2020-09-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0002_listenerfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='listenerfeedback',
            name='hit',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listenerfeedback',
            name='listen_again',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listenerfeedback',
            name='listen_another',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listenerfeedback',
            name='lyrical_value',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listenerfeedback',
            name='playlist',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listenerfeedback',
            name='production_value',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listenerfeedback',
            name='vocal_perf',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listenerfeedback',
            name='watch_live',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default=1, max_length=12),
            preserve_default=False,
        ),
    ]
