# Generated by Django 3.1.1 on 2020-09-21 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0005_listenerquestionnaire_added_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listenerquestionnaire',
            old_name='added_by',
            new_name='user',
        ),
    ]
