# Generated by Django 3.1.1 on 2020-09-21 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0007_auto_20200921_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listenerquestionnaire',
            old_name='user',
            new_name='added_by',
        ),
    ]
