# Generated by Django 3.1.1 on 2020-09-25 16:58

import audiofield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0010_auto_20200922_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='listenerfeedback',
            name='audio_file',
            field=audiofield.fields.AudioField(blank=True, help_text='Allowed type - .mp3, .wav, .ogg', upload_to='your/upload/dir'),
        ),
    ]
