# Generated by Django 3.1.1 on 2020-10-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0013_remove_listenerfeedback_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='listenerfeedback',
            name='voicenote',
            field=models.FileField(default=1, upload_to='media/voicenotes'),
            preserve_default=False,
        ),
    ]
