# Generated by Django 3.1.1 on 2020-10-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0014_listenerfeedback_voicenote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listenerfeedback',
            name='voicenote',
            field=models.FileField(blank=True, null=True, upload_to='media/voicenotes'),
        ),
    ]
