# Generated by Django 3.1.1 on 2020-11-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0015_auto_20201028_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listenerfeedback',
            name='lyrical_value',
        ),
        migrations.AddField(
            model_name='listenerfeedback',
            name='songwriting',
            field=models.CharField(choices=[('poor', 'Poor'), ('so-so', 'So so'), ('average', 'Average'), ('good', 'Good'), ('excellent', 'Excellent')], default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listenerfeedback',
            name='production_value',
            field=models.CharField(choices=[('poor', 'Poor'), ('not-great', 'Not great'), ('average', 'Average'), ('good', 'Good'), ('excellent', 'Excellent')], max_length=12),
        ),
        migrations.AlterField(
            model_name='listenerfeedback',
            name='vocal_perf',
            field=models.CharField(choices=[('poor', 'Poor'), ('so-so', 'So so'), ('average', 'Average'), ('good', 'Good'), ('excellent', 'Excellent')], max_length=12),
        ),
    ]
