# Generated by Django 3.1.1 on 2020-09-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='User_type',
            field=models.CharField(choices=[('musician', 'Musician'), ('listener', 'Listener')], max_length=12),
        ),
    ]
