# Generated by Django 3.1.1 on 2020-09-30 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_song'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Song',
        ),
    ]
