# Generated by Django 3.1.1 on 2020-09-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usertype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('User_type', models.CharField(choices=[('musician', 'Musician'), ('listener', 'Listener')], max_length=12)),
            ],
        ),
    ]
