# Generated by Django 3.1.1 on 2020-09-10 14:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0002_auto_20200910_1333'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usertype',
            new_name='Profile',
        ),
    ]
