# Generated by Django 3.1.1 on 2020-09-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20200910_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city_of_residence',
            field=models.CharField(choices=[('bath', 'Bath'), ('birmingham', 'Birmingham'), ('bradford', 'Bradford'), ('brighton & hove', 'Brighton & Hove'), ('bristol', 'Bristol'), ('cambridge', 'Cambridge'), ('canterbury', 'Canterbury'), ('carlisle', 'Carlisle'), ('chester', 'Chester'), ('chichester', 'Chichester'), ('coventry', 'Coventry'), ('derby', 'Derby'), ('durham', 'Durham'), ('ely', 'Ely'), ('exeter', 'Exeter'), ('gloucester', 'Gloucester'), ('Hereford', 'Hereford'), ('kingston upon Hull', 'Kingston upon Hull'), ('lancaster', 'Lancaster'), ('leeds', 'Leeds'), ('leicester', 'Leicester'), ('lichfield', 'Lichfield'), ('lincoln', 'Lincoln'), ('liverpool', 'Liverpool'), ('london', 'London'), ('manchester', 'Manchester'), ('newcastle upon tyne', 'Newcastle upon Tyne'), ('norwich', 'Norwich'), ('nottingham', 'Nottingham'), ('oxford', 'Oxford'), ('peterborough', 'Peterborough'), ('plymouth', 'Plymouth'), ('portsmouth', 'Portsmouth'), ('preston', 'Preston'), ('ripon', 'Ripon'), ('salford', 'Salford'), ('salisbury', 'Salisbury'), ('sheffield', 'Sheffield'), ('southampton', 'Southampton'), ('st albans', 'St Albans'), ('stoke-on-trent', 'Stoke-on-Trent'), ('sunderland', 'Sunderland'), ('truro', 'Truro'), ('wakefield', 'Wakefield'), ('wells', 'Wells'), ('westminster', 'Westminster'), ('winchester', 'Winchester'), ('wolverhampton', 'Wolverhampton'), ('worcester', 'Worcester'), ('york', 'York')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
