# Generated by Django 3.1.1 on 2020-09-15 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_profile_city_of_residence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
