# Generated by Django 3.1.1 on 2020-09-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SongUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('song_genre', models.CharField(choices=[('rap', 'Rap'), ('rnb', 'RnB'), ('drill', 'Drill'), ('hip hop', 'Hip Hop'), ('grime', 'Grime'), ('afro swing', 'Afro Swing'), ('reggae', 'Reggae'), ('pop', 'Pop'), ('dubstep', 'Dubstep'), ('jazz', 'Jazz'), ('drum and bass', 'Drum and Bass'), ('rock', 'Rock'), ('heavy metal', 'Heavy Metal')], max_length=100)),
                ('song', models.FileField(upload_to='media/songs')),
            ],
        ),
    ]
